### ISSUE TITLE
Vlan default_ret defaults to IPRecord instead of Record

### ISSUE THREAD

**Issue by funzoneq** [digitalocean/pynetbox#102]
Version pynetbox==3.4.7

I have a vlan named 423 in netbox. When I try to apply it to an interface I get the following error:

```
{'_full_cache': [('id', 2969),
                 ('site', None),
                 ('group', None),
                 ('vid', 423),
                 ('name', '423'),
                 ('tenant', None),
                 ('status', {'label': 'Active', 'value': 1}),
                 ('role',
                  {'id': 5,
                   'name': 'Customer access',
                   'slug': 'customer-access',
                   'url': 'https://netbox.example.com/api/ipam/roles/5/'}),
                 ('description', ''),
                 ('tags', []),
                 ('display_name', '423 (423)'),
                 ('custom_fields', {}),
                 ('created', '2018-07-19'),
                 ('last_updated', '2018-07-19T23:14:26.045543Z')],
 '_index_cache': [('id', 2969),
                  ('site', None),
                  ('group', None),
                  ('vid', 423),
                  ('name', '423'),
                  ('tenant', None),
                  ('status', 1),
                  ('role', 5),
                  ('description', ''),
                  ('tags', []),
                  ('display_name', '423 (423)'),
                  ('custom_fields', {}),
                  ('created', '2018-07-19'),
                  ('last_updated', '2018-07-19T23:14:26.045543Z')],
 'api_kwargs': {'base_url': 'https://netbox.example.com/api',
                'private_key': None,
                'private_key_file': None,
                'ssl_verify': True,
                'token': '123456',
                'version': '2.4'},
 'created': '2018-07-19',
 'custom_fields': {},
 **'default_ret': <class 'pynetbox.lib.response.IPRecord'>,**
 'description': '',
 'display_name': '423 (423)',
 'endpoint_meta': {'url': 'https://netbox.example.com/api/ipam/vlans'},
 'group': None,
 'id': 2969,
 'last_updated': '2018-07-19T23:14:26.045543Z',
 'name': '423',
 'role': Customer access,
 'site': None,
 'status': Active,
 'tags': [],
 'tenant': None,
 'vid': 423}
```

```
{'_full_cache': [('id', 11293),
                 ('device',
                  {'display_name': 'cas04-ashfieldrd91-ath',
                   'id': 383,
                   'name': 'cas04-ashfieldrd91-ath',
                   'url': 'https://netbox.example.com/api/dcim/devices/383/'}),
                 ('name', 'xe-0/0/0'),
                 ('form_factor', {'label': 'SFP+ (10GE)', 'value': 1200}),
                 ('enabled', True),
                 ('lag', None),
                 ('mtu', None),
                 ('mac_address', None),
                 ('mgmt_only', False),
                 ('description', ''),
                 ('is_connected', True),
                 ('interface_connection',
                  {'connection_status': {'label': 'Connected', 'value': True},
                   'id': 163,
                   'interface': {'device': {'display_name': 'cpe01-example-ath',
                                            'id': 411,
                                            'name': 'cpe01-example-ath',
                                            'url': 'https://netbox.example.com/api/dcim/devices/411/'},
                                 'id': 12272,
                                 'name': 'xe-0/1/1',
                                 'url': 'https://netbox.example.com/api/dcim/interfaces/12272/'}}),
                 ('circuit_termination', None),
                 ('mode', None),
                 ('untagged_vlan', None),
                 ('tagged_vlans', []),
                 ('tags', [])],
 '_index_cache': [('id', 11293),
                  ('device', 383),
                  ('name', 'xe-0/0/0'),
                  ('form_factor', 1200),
                  ('enabled', True),
                  ('lag', None),
                  ('mtu', None),
                  ('mac_address', None),
                  ('mgmt_only', False),
                  ('description', ''),
                  ('is_connected', True),
                  ('interface_connection', 163),
                  ('circuit_termination', None),
                  ('mode', None),
                  ('untagged_vlan', None),
                  ('tagged_vlans', []),
                  ('tags', [])],
 'api_kwargs': {'base_url': 'https://netbox.example.com/api',
                'private_key': None,
                'private_key_file': None,
                'ssl_verify': True,
                'token': '123456',
                'version': '2.4'},
 'circuit_termination': None,
 'default_ret': <class 'pynetbox.lib.response.Record'>,
 'description': '',
 'device': cas04-ashfieldrd91-ath,
 'enabled': True,
 'endpoint_meta': {'url': 'https://netbox.example.com/api/dcim/interfaces'},
 'form_factor': SFP+ (10GE),
 'id': 11293,
 'interface_connection': xe-0/1/1,
 'is_connected': True,
 'lag': None,
 'mac_address': None,
 'mgmt_only': False,
 'mode': 200,
 'mtu': None,
 'name': 'xe-0/0/0',
 'tagged_vlans': [423],
 'tags': [],
 'untagged_vlan': None}
Traceback (most recent call last):
  File "assign-vlan-to-ports.py", line 57, in <module>
    i.save()
  File "/Users/avermeer/Documents/netbox/lib/python3.6/site-packages/pynetbox/lib/response.py", line 271, in save
    if req.put(self.serialize()):
  File "/Users/avermeer/Documents/netbox/lib/python3.6/site-packages/pynetbox/lib/query.py", line 265, in put
    data=json.dumps(data),
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'IPRecord' is not JSON serializable
```

API Response:
```
{
  "count": 2,
  "next": null,
  "previous": null,
  "results": [
    {
      "id": 5176,
      "site": {
        "id": 1,
        "url": "https://netbox.example.com/api/dcim/sites/1/",
        "name": "2ndSt720-oak",
        "slug": "2ndst720-oak"
      },
      "group": {
        "id": 5,
        "url": "https://netbox.example.com/api/ipam/vlan-groups/5/",
        "name": "2002",
        "slug": "2002"
      },
      "vid": 423,
      "name": "423",
      "tenant": null,
      "status": {
        "value": 1,
        "label": "Active"
      },
      "role": {
        "id": 5,
        "url": "https://netbox.example.com/api/ipam/roles/5/",
        "name": "Customer access",
        "slug": "customer-access"
      },
      "description": "",
      "tags": [],
      "display_name": "423 (423)",
      "custom_fields": {},
      "created": "2018-08-08",
      "last_updated": "2018-08-08T12:09:44.241872Z"
    },
    {
      "id": 769,
      "site": {
        "id": 5,
        "url": "https://netbox.example.com/api/dcim/sites/5/",
        "name": "65th1400-emy",
        "slug": "65th1400-emy"
      },
      "group": {
        "id": 3,
        "url": "https://netbox.example.com/api/ipam/vlan-groups/3/",
        "name": "2000",
        "slug": "2000"
      },
      "vid": 423,
      "name": "423",
      "tenant": null,
      "status": {
        "value": 1,
        "label": "Active"
      },
      "role": {
        "id": 5,
        "url": "https://netbox.example.com/api/ipam/roles/5/",
        "name": "Customer access",
        "slug": "customer-access"
      },
      "description": "",
      "tags": [],
      "display_name": "423 (423)",
      "custom_fields": {},
      "created": "2018-07-19",
      "last_updated": "2018-07-19T18:51:05.687666Z"
    }
  ]
}
```

**Comment by zachmoody** [comment]
Suspect this is similar to the issue in #90 - We're removing netaddr and with it the IPrecord object to fix issues like this in 4.0. Hoping to have it out soon.
