### ISSUE TITLE
Python 3 support (unicode is replaced by str and str is replaced by bytes)

### ISSUE THREAD

**Issue by mvangoor** [digitalocean/pynetbox#11]
Hi,

I am running python3 and run into an issue with this library.
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    conn_nb.dcim.devices.all()
  File "/usr/lib/python3.4/site-packages/pynetbox/lib/endpoint.py", line 119, in all
    for i in req.get()
  File "/usr/lib/python3.4/site-packages/pynetbox/lib/endpoint.py", line 119, in <listcomp>
    for i in req.get()
  File "/usr/lib/python3.4/site-packages/pynetbox/lib/response.py", line 63, in __init__
    self._parse_values(values)
  File "/usr/lib/python3.4/site-packages/pynetbox/lib/response.py", line 129, in _parse_values
    v = lookup(v, api_kwargs=self.api_kwargs)
  File "/usr/lib/python3.4/site-packages/pynetbox/lib/response.py", line 269, in __init__
    super(IPRecord, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/pynetbox/lib/response.py", line 63, in __init__
    self._parse_values(values)
  File "/usr/lib/python3.4/site-packages/pynetbox/lib/response.py", line 297, in _parse_values
    if isinstance(v, (str, unicode)):
NameError: name 'unicode' is not defined

I checked and unicode no longer exists and is replaced by str and str is replaced by bytes in python 3.

Based on my very limited knowledge of python I would suggest something like:
if sys.version_info.major < 3:
    if isinstance(v, (str, unicode)):
else:
    if isinstance(v, (bytes, str)):

**Comment by zachmoody** [comment]
A previous issue mentioned the six library might provide a cleaner approach. I'm hoping to address py3 compatibility as a whole pretty soon. Need to get tests working then address whatever comes out of those. I'll leave this issue open to reference something we know is broken.
