### ISSUE TITLE
RequestError thrown when trying to access ipam.ip_addresses

### ISSUE THREAD

**Issue by konaya** [digitalocean/pynetbox#167]
I have a working session, as shown:

```
>>> len(nb.dcim.devices.all())
550
>>> 
```

Trying to get all IP addresses fails, as shown:

```
>>> nb.ipam.ip_addresses.all()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/konaya/.local/lib/python3.7/site-packages/pynetbox/core/endpoint.py", line 98, in all
    return [self._response_loader(i) for i in req.get()]
  File "/home/konaya/.local/lib/python3.7/site-packages/pynetbox/core/query.py", line 239, in get
    return req_all(self.url)
  File "/home/konaya/.local/lib/python3.7/site-packages/pynetbox/core/query.py", line 232, in req_all
    req = make_request(next_url)
  File "/home/konaya/.local/lib/python3.7/site-packages/pynetbox/core/query.py", line 214, in make_request
    raise RequestError(req)
pynetbox.core.query.RequestError: The requested url: http://netbox.[REDACTED]/api/ipam/ip-addresses/?limit=1000&offset=1050 could not be found.
>>>  
```

Python 3.7.3, pynetbox 4.0.6, Netbox 2.5.12

I'm not sure if it's relevant, but I'm using Netbox over HTTPS. I have no idea why the thrown RequestError is showing an http:// address. Surfing to the thrown address with a web browser works just fine, by the way.

**Comment by konaya** [comment]
Oh, uh, never mind. It was an nginx misconfiguration issue. Netbox thought it was being served over HTTP, so it sent such a `next` address. Looking at it in the browser works because HSTS, but pynetbox got treated to a 301 redirect to https://www.eff.org/https-everywhere. Solved!
