### ISSUE TITLE
requests.exceptions.MissingSchema: error while executing api query 

### ISSUE THREAD

**Issue by chayakn** [digitalocean/pynetbox#172]
Trying to retrieve netbox details through pynetbox
while executing any query eg: api.ipam.prefixes.get(28702) throwing schema error.

for reference i could see curl method working fine.

>>> import pynetbox
>>> api = pynetbox.api('netbox.net.thmulti.com',ssl_verify=False,token="9acac257113c24d3bef0d0ea625ca4466e996c2")
>>> api.ipam.prefixes.get(28702)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/GIN_Engineer/.local/lib/python3.6/site-packages/pynetbox/core/endpoint.py", line 155, in get
    return self._response_loader(req.get())
  File "/home/GIN_Engineer/.local/lib/python3.6/site-packages/pynetbox/core/query.py", line 239, in get
    return req_all(self.url)
  File "/home/GIN_Engineer/.local/lib/python3.6/site-packages/pynetbox/core/query.py", line 217, in req_all
    req = make_request(url)
  File "/home/GIN_Engineer/.local/lib/python3.6/site-packages/pynetbox/core/query.py", line 210, in make_request
    req = requests.get(url, headers=headers, verify=self.ssl_verify)
  File "/home/GIN_Engineer/.local/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/GIN_Engineer/.local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/GIN_Engineer/.local/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/home/GIN_Engineer/.local/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/GIN_Engineer/.local/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/home/GIN_Engineer/.local/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'netbox.net.thmulti.com/api/ipam/prefixes/28702/': No schema supplied. Perhaps you meant http://netbox.net.thmulti.com/api/ipam/prefixes/28702/?
>>> 

curl -k -H "Accept: application/json; indent=4;" -H "Authorization: Token 9acac257113c24d3bef0d0ea625ca4466e996c29" https://netbox.net.thmulti.com/api/ipam/prefixes/28702/
{
    "id": 28702,
    "family": 4,
    "prefix": "1.1.1.0/24",
    "site": {
        "id": 58,
        "url": "https://netbox.net.thmulti.com/api/dcim/sites/58/",
        "name": "Hong-Kong",
        "slug": "hong-kong"
    },
    "vrf": null,
    "tenant": null,
    "vlan": null,
    "status": {
        "value": 1,
        "label": "Active"
    },
    "role": null,
    "is_pool": false,
    "description": "discovered by script 2019-02-28 20:20:09",
    "tags": [],
    "custom_fields": {
        "cloud_provider": null,
        "cloud_region": null,
        "Gateway": null,
        "v_group": null,
        "v_net": null
    },
    "created": "2019-02-28",
    "last_updated": "2019-02-28T20:20:10.027862Z"

**Comment by zachmoody** [comment]
Try instantiating with `https://netbox.net.thmulti.com` instead of just `netbox.net.thmulti.com`.
