### ISSUE TITLE
Trouble deleting VLAN

### ISSUE THREAD

**Issue by craigbruenderman** [digitalocean/pynetbox#295]
I'm unclear on how to use delete_vlan(). It seems it's expecting vid, which would be the dot1q tag, but that tag is not globally unique. I was expecting to delete via the primary key 'id' (2927 in this case), but that's not working. Am I missing something?

```
>>> vlans = netbox.ipam.get_vlans(site_id = sites[0].get('id'))
>>>
>>> v = vlans[0]
>>> v
{'id': 2927, 'url': 'http://netbox-dev.cbadnms.com/api/ipam/vlans/2927/', 'site': {'id': 429, 'url': 'http://netbox-dev.cbadnms.com/api/dcim/sites/429/', 'name': 'Banigan', 'slug': 'Banigan-DC'}, 'group': None, 'vid': 101, 'name': 'Data VLAN', 'tenant': {'id': 25498, 'url': 'http://netbox-dev.cbadnms.com/api/tenancy/tenants/25498/', 'name': 'CBTS', 'slug': 'cbts'}, 'status': {'value': 'active', 'label': 'Active'}, 'role': None, 'description': '', 'tags': [], 'display_name': 'Data VLAN (101)', 'custom_fields': {}, 'created': '2020-10-14', 'last_updated': '2020-10-14T21:21:31.661642Z', 'prefix_count': None}
>>>
>>> netbox.ipam.delete_vlan(v.get('id'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/craigb/.pyenv/versions/3.8.5/lib/python3.8/site-packages/netbox/ipam.py", line 325, in delete_vlan
    raise exceptions.NotFoundException('vlan: {}'.format(vid)) from None
netbox.exceptions.NotFoundException: Unable to found vlan: 2927
```

**Comment by markkuleinio** [comment]
It looks like you are not using `pynetbox` but something else (`netbox`?), so you need to look for help somewhere else.

**Comment by tyler-8** [comment]
@markkuleinio has it right - this doesn't appear to be the `pynetbox` library but instead the `python-netbox` library: https://github.com/jagter/python-netbox

**Comment by craigbruenderman** [comment]
Totally right. Sorry guys. 

--
Craig Bruenderman
502-548-1100

**Comment by markkuleinio** [comment]
No worries. You can close the issue in GitHub.
