### ISSUE TITLE
Python3 issues with basestring

### ISSUE THREAD

**Issue by lamiskin** [digitalocean/pynetbox#3]
I've run in to an issue with the use of ```basestring```, this seems to be deprecated in Python3 and instead the use of ```str``` is suggested.

There's a few occurrences within ``lib/response.py``, which locally I've tried replacing with ```str```, which seems to be working.

Example traceback from p3.4:
```
>>> nb.dcim.devices.all()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/NDC-Dev-Envs/ndc-pynetbox/lib/python3.4/site-packages/pynetbox/lib/endpoint.py", line 111, in all
    for i in req.get()
  File "/opt/NDC-Dev-Envs/ndc-pynetbox/lib/python3.4/site-packages/pynetbox/lib/endpoint.py", line 111, in <listcomp>
    for i in req.get()
  File "/opt/NDC-Dev-Envs/ndc-pynetbox/lib/python3.4/site-packages/pynetbox/lib/response.py", line 47, in __init__
    self._parse_values(values)
  File "/opt/NDC-Dev-Envs/ndc-pynetbox/lib/python3.4/site-packages/pynetbox/lib/response.py", line 102, in _parse_values
    setattr(self, k, lookup(v, api_kwargs=self.api_kwargs))
  File "/opt/NDC-Dev-Envs/ndc-pynetbox/lib/python3.4/site-packages/pynetbox/lib/response.py", line 242, in __init__
    super(IPRecord, self).__init__(*args, **kwargs)
  File "/opt/NDC-Dev-Envs/ndc-pynetbox/lib/python3.4/site-packages/pynetbox/lib/response.py", line 47, in __init__
    self._parse_values(values)
  File "/opt/NDC-Dev-Envs/ndc-pynetbox/lib/python3.4/site-packages/pynetbox/lib/response.py", line 275, in _parse_values
    if isinstance(v, basestring):
NameError: name 'basestring' is not defined
```

I can submit a pull request with the changes, if there is no objections.

**Comment by zachmoody** [comment]
There was a reason for using it instead of `str`, but I can't remember the details.  :(

I'd say py3 compatibility is more important than a corner case that might not even be relevant anymore though. We might want to throw `unicode` in with `str` so we're doing the equivalent of `basestring` though. Happy to take a PR for it if you'd like or I should be able to get to it soon'ish.

**Comment by s-takehana** [comment]
Hi,

If there is a reason, how is [six.string_types](https://pythonhosted.org/six/#six.string_types)?
https://stackoverflow.com/questions/11301138/how-to-check-if-variable-is-string-with-python-2-and-3-compatibility

This issue is critical for Python3 users.

**Comment by zachmoody** [comment]
Hope this PR unblocks you all. I'm hesitant to include six if this is the only py3 incompatibility. Planning on fully supporting py3 as soon as I can get some time to get tests working.
