### ISSUE TITLE
full_details doesn't add token

### ISSUE THREAD

**Issue by funzoneq** [digitalocean/pynetbox#32]
I'm using pynetbox version 3.0.1 and netbox with LOGIN_REQUIRED = True and I see the following behaviour:

```
import requests
import logging
from pprint import pprint

# These two lines enable debugging at httplib level (requests->urllib3->http.client)
# You will see the REQUEST, including HEADERS and DATA, and RESPONSE with HEADERS but without DATA.
# The only thing missing will be the response.body which is not logged.
try:
    import http.client as http_client
except ImportError:
    # Python 2
    import httplib as http_client
http_client.HTTPConnection.debuglevel = 1

# You must initialize logging, otherwise you'll not see debug output.
logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)
requests_log = logging.getLogger("requests.packages.urllib3")
requests_log.setLevel(logging.DEBUG)
requests_log.propagate = True

url = 'https://netbox.example.com'
token = 'abcdefghijklmnopqrstuvwxyz'

try:
    import pynetbox
    from netaddr import *
except ImportError, e:
    sys.exit("Please install required python modules: pynetbox netaddr")

try:
    netbox = pynetbox.api(url, token=token)
except AttributeError:
    sys.exit("Failed to connect to netbox instance")

for host in netbox.virtualization.virtual_machines.filter(status=1):
    pprint(host)
    pprint(vars(host))
```

```
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): netbox.example.net
send: 'GET /api/ HTTP/1.1\r\nHost: netbox.example.net\r\nConnection: keep-alive\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nUser-Agent: python-requests/2.10.0\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: nginx/1.10.3 (Ubuntu)
header: Date: Wed, 07 Feb 2018 09:38:23 GMT
header: Content-Type: application/json
header: Content-Length: 353
header: Connection: keep-alive
header: Allow: GET, HEAD, OPTIONS
header: X-Frame-Options: SAMEORIGIN
header: API-Version: 2.2
header: Vary: Accept, Cookie
header: P3P: CP="ALL DSP COR PSAa PSDa OUR NOR ONL UNI COM NAV"
header: X-Cache-Status: MISS
DEBUG:requests.packages.urllib3.connectionpool:"GET /api/ HTTP/1.1" 200 353

INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): netbox.example.net
send: 'GET /api/virtualization/virtual-machines/?status=1 HTTP/1.1\r\nHost: netbox.example.net\r\nConnection: keep-alive\r\nAccept-Encoding: gzip, deflate\r\naccept: application/json; version=2.2;\r\nUser-Agent: python-requests/2.10.0\r\nauthorization: Token abcdefghijklmnopqrstuvwxyz\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: nginx/1.10.3 (Ubuntu)
header: Date: Wed, 07 Feb 2018 09:38:23 GMT
header: Content-Type: application/json
header: Content-Length: 2687
header: Connection: keep-alive
header: Allow: GET, POST, HEAD, OPTIONS
header: X-Frame-Options: SAMEORIGIN
header: API-Version: 2.2
header: Vary: Accept, Cookie
header: P3P: CP="ALL DSP COR PSAa PSDa OUR NOR ONL UNI COM NAV"
header: X-Cache-Status: MISS
DEBUG:requests.packages.urllib3.connectionpool:"GET /api/virtualization/virtual-machines/?status=1 HTTP/1.1" 200 2687
dhcp01-smarket55-sjc

INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): netbox.example.net
send: 'GET /api/ipam/ip-addresses/91/ HTTP/1.1\r\nHost: netbox.example.net\r\nConnection: keep-alive\r\nAccept-Encoding: gzip, deflate\r\naccept: application/json; version=2.2;\r\nUser-Agent: python-requests/2.10.0\r\n\r\n'
reply: 'HTTP/1.1 403 Forbidden\r\n'
header: Server: nginx/1.10.3 (Ubuntu)
header: Date: Wed, 07 Feb 2018 09:38:24 GMT
header: Content-Type: application/json
header: Content-Length: 58
header: Connection: keep-alive
header: Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
header: X-Frame-Options: SAMEORIGIN
header: API-Version: 2.2
header: Vary: Accept, Cookie
DEBUG:requests.packages.urllib3.connectionpool:"GET /api/ipam/ip-addresses/91/ HTTP/1.1" 403 58
Traceback (most recent call last):
  File "bug.py", line 38, in <module>
    pprint(vars(host))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pprint.py", line 59, in pprint
    printer.pprint(object)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pprint.py", line 117, in pprint
    self._format(object, self._stream, 0, 0, {}, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pprint.py", line 140, in _format
    rep = self._repr(object, context, level - 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pprint.py", line 226, in _repr
    self._depth, level)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pprint.py", line 238, in format
    return _safe_repr(object, context, maxlevels, level)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pprint.py", line 282, in _safe_repr
    vrepr, vreadable, vrecur = saferepr(v, context, maxlevels, level)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pprint.py", line 323, in _safe_repr
    rep = repr(object)
  File "/Library/Python/2.7/site-packages/pynetbox/lib/response.py", line 103, in __repr__
    return str(self)
  File "/Library/Python/2.7/site-packages/pynetbox/lib/response.py", line 97, in __str__
    getattr(self, 'name', None) or
  File "/Library/Python/2.7/site-packages/pynetbox/lib/response.py", line 77, in __getattr__
    if self.full_details():
  File "/Library/Python/2.7/site-packages/pynetbox/lib/response.py", line 176, in full_details
    self._parse_values(req.get())
  File "/Library/Python/2.7/site-packages/pynetbox/lib/query.py", line 215, in get
    return req_all(self.url)
  File "/Library/Python/2.7/site-packages/pynetbox/lib/query.py", line 197, in req_all
    req = make_request(url)
  File "/Library/Python/2.7/site-packages/pynetbox/lib/query.py", line 194, in make_request
    raise RequestError(req)
pynetbox.lib.query.RequestError: The request failed with code 403 Forbidden
```

As you can see, the third request to /ipam/ is missing the auth token. My guess is that it's missing because we don't forward it here: https://github.com/digitalocean/pynetbox/blob/master/pynetbox/lib/response.py#L172

**Comment by zachmoody** [comment]
Yeah, that doesn't look right. Let me try and replicate it today. Your PR looks good, just want to verify the behavior and your fix. Unless you want to throw a test in your PR. Thanks for the heads up!
