### ISSUE TITLE
KeyError when trying to get nb.dcim.device_types.all()

### ISSUE THREAD

**Issue by anthony548** [digitalocean/pynetbox#339]
Hello everyone, 

I wrote a script a few months ago and now I can't get it to work again.Do you have any idea ?

Here is the Traceback

```python3
Traceback (most recent call last):
  File "/home/anthony/add_devices.py", line 17, in <module>
    nb = Netbox('mynetboxinstance','TOKEN')
  File "/home/anthony/netbox.py", line 44, in __init__
    self.update_devices_model()
  File "/home/anthony/netbox.py", line 93, in update_devices_model
    self.devices_model = self.nb.dcim.device_types.all()
  File "/home/anthony/.local/lib/python3.8/site-packages/pynetbox/core/endpoint.py", line 101, in all
    return response_loader(req.get(), self.return_obj, self)
  File "/home/anthony/.local/lib/python3.8/site-packages/pynetbox/core/query.py", line 356, in get
    return req_all_threaded(add_params)
  File "/home/anthony/.local/lib/python3.8/site-packages/pynetbox/core/query.py", line 336, in req_all_threaded
    req = self._make_call(add_params=add_params)
  File "/home/anthony/.local/lib/python3.8/site-packages/pynetbox/core/query.py", line 280, in _make_call
    raise RequestError(req)
pynetbox.core.query.RequestError: The request failed with code 500 Internal Server Error: {'error': "'None'", 'exception': 'KeyError', 'netbox_version': '2.10.6', 'python_version': '3.8.7'}
```

Regards

**Comment by anthony548** [comment]
The problem was on my data. 
I created a loop to get all of them one by one:
```python3
        for i in range(1,500,1):
            print(i)
            device = nb.dcim.device_types.get(i)
            print(device)
            if device is not None:
                device.save()
            print("-----------------------")
```
The script stopped at i=470, I went to the device type 470, then just edit and save.
The subdevice_role was "None" instead of ""
