### ISSUE TITLE
RecordSet __len__ raises error

### ISSUE THREAD

**Issue by Dimaqa** [digitalocean/pynetbox#356]
If you call len() before iteration you will get AttributeError
```
>>> a = nb2.dcim.platfroms.all()
>>> len(a)
Traceback (most recent call last):
  File "local-packages\Python37\site-packages\pynetbox\core\response.py", line 88, in __len__
    return self.request.count
AttributeError: 'Request' object has no attribute 'count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "local-packages\Python37\site-packages\pynetbox\core\response.py", line 90, in __len__
    self._response_cache.append(next(self.response))
  File "local-packages\Python37\site-packages\pynetbox\core\query.py", line 312, in get
    req = self._make_call(add_params=add_params)
  File "local-packages\Python37\site-packages\pynetbox\core\query.py", line 282, in _make_call
    raise RequestError(req)
pynetbox.core.query.RequestError: The requested url: https://netbox/api/dcim/platfroms/?limit=0 could not be found.
```

**Comment by Dimaqa** [comment]
Oh, my bad, there was typo in **platfroms**, but calling get_count instead of count still probably a good idea
