### ISSUE TITLE
How add interface (create)

### ISSUE THREAD

**Issue by alexeysorok** [digitalocean/pynetbox#361]
How to add  an interface to a device
I tried using the following code 

```
import pynetbox

nb = pynetbox.api(url='http://netbox', token='')
response = nb.dcim.interfaces.create(
     device=device.id,
     name="LAN",
     type="1000BASE-T (1GE)",        
     enabled=True,
)
```
This Error: 
Traceback (most recent call last):
  File "c:/src/test/NetBox/Untitled-1.py", line 23, in <module>
    response = nb.dcim.interfaces.create(
  File "C:\src\test\NetBox\env\lib\site-packages\pynetbox\core\endpoint.py", line 271, in create
    req = Request(
  File "C:\src\test\NetBox\env\lib\site-packages\pynetbox\core\query.py", line 386, in post
    return self._make_call(verb="post", data=data)
  File "C:\src\test\NetBox\env\lib\site-packages\pynetbox\core\query.py", line 282, in _make_call
    raise RequestError(req)
pynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'type': ['1000BASE-T (1GE) is not a valid choice.']}

**How can this be done correctly?**

**Comment by zachmoody** [comment]
type here should be `1000base-t`. It aligns with the values for `interface:type` in `/api/dcim/_choices/`. Iirc, that might be an `OPTIONS` call too in more recent NetBox versions.
