### ISSUE TITLE
get primary_ip incorrectly formatted url when using virtualization

### ISSUE THREAD

**Issue by jord-bh** [digitalocean/pynetbox#42]
Hi,

I have one device (test1), and one virtual machine (test2). Both entities have an ip address bound in the GUI.

I have instantiated netbox:
```
nb = pynetbox.api(
    'https://netbox.domain.tld',
    token='xxxxxxx',
)
```

I try loading the id and primary_ip from the device:
```
>>> nb.dcim.devices.get(name='test1').id                                                                                                                                                                  
43
>>> nb.dcim.devices.get(name='test1').primary_ip
10.0.12.15/27
```

I  then proceeded to do the same for the virtual machine,
```
>>> nb.virtualization.virtual_machines.get(name='test2').id        
2
>>> nb.virtualization.virtual_machines.get(name='test2').primary_ip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jord/.virtualenvs/netbox/lib64/python3.6/site-packages/pynetbox/lib/response.py", line 103, in __repr__
    return str(self)
  File "/home/jord/.virtualenvs/netbox/lib64/python3.6/site-packages/pynetbox/lib/response.py", line 97, in __str__
    getattr(self, 'name', None) or
  File "/home/jord/.virtualenvs/netbox/lib64/python3.6/site-packages/pynetbox/lib/response.py", line 77, in __getattr__
    if self.full_details():
  File "/home/jord/.virtualenvs/netbox/lib64/python3.6/site-packages/pynetbox/lib/response.py", line 178, in full_details
    self._parse_values(req.get())
  File "/home/jord/.virtualenvs/netbox/lib64/python3.6/site-packages/pynetbox/lib/query.py", line 216, in get
    
  File "/home/jord/.virtualenvs/netbox/lib64/python3.6/site-packages/pynetbox/lib/query.py", line 198, in req_all
    def req_all(url):
  File "/home/jord/.virtualenvs/netbox/lib64/python3.6/site-packages/pynetbox/lib/query.py", line 190, in make_request
    
  File "/home/jord/.virtualenvs/netbox/lib64/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/jord/.virtualenvs/netbox/lib64/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/jord/.virtualenvs/netbox/lib64/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jord/.virtualenvs/netbox/lib64/python3.6/site-packages/requests/sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/jord/.virtualenvs/netbox/lib64/python3.6/site-packages/requests/sessions.py", line 640, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/jord/.virtualenvs/netbox/lib64/python3.6/site-packages/requests/sessions.py", line 218, in resolve_redirects
    **adapter_kwargs
  File "/home/jord/.virtualenvs/netbox/lib64/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/jord/.virtualenvs/netbox/lib64/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='netbox.bahnhof.netapi', port=443): Max retries exceeded with url: /ipam/ip-addresses/1715/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fabf52556a0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

The param "host='netbox.domain.tldapi'" looks rather suspicious, but I fail to understand why it would be different when using the virtualization object, and even differently between the .id and .primary_ip attribute inside that object. Does anybody understand this better than I?

**Comment by zachmoody** [comment]
We probably need a custom object similar to `Device` for VirtualMachines so that it knows attributes like `primary_ip` are IPAddress objects. I'll have a look at it.

**Comment by jord-bh** [comment]
Worked perfectly, I just wanted to send a thank you and kudos on the impressive response time!
