### ISSUE TITLE
interfaces.get: raise ValueError get() returned more than one result

### ISSUE THREAD

**Issue by tiago-cruz-movile** [digitalocean/pynetbox#47]
Environment: pynetbox (3.2.0)

- device with just eth0:

```
>>> nbmovile.dcim.interfaces.get(device='alog10')
eth0
```

- device with eth0 and eth1:

```
>>> nbmovile.dcim.interfaces.get(device='mcloud8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pynetbox/lib/endpoint.py", line 161, in get
    raise ValueError('get() returned more than one result.')
ValueError: get() returned more than one result.
```

**Comment by zachmoody** [comment]
That's expected, you'll want to use `.filter()` if your query has the potential for more than one result.
