### ISSUE TITLE
Error While Creating a range prefix.available_ips.create([{} for i in range(2)]) 

### ISSUE THREAD

**Issue by amb1s1** [digitalocean/pynetbox#50]
When I try to create a range of available ips, I get a 500 internal server error.

Here is the output:
```
>>> nb = pynetbox.api(url=url,token=token)
>>> prefix = nb.ipam.prefixes.get(q='10.10.10.0/24')
>>> prefix
10.10.10.0/24
>>> prefix.available_ips.create([{} for i in range(2)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/davidg/Library/Python/2.7/lib/python/site-packages/pynetbox/lib/endpoint.py", line 364, in create
    return Request(**self.request_kwargs).post(data)
  File "/Users/davidg/Library/Python/2.7/lib/python/site-packages/pynetbox/lib/query.py", line 297, in post
    raise RequestError(req)
pynetbox.lib.query.RequestError: The request failed with code 500 Internal Server Error
>>> prefix.available_ips.create()
{u'status': 1, u'description': u'', u'nat_inside': None, u'role': None, u'vrf': None, u'address': u'10.10.10.13/24', u'interface': None, u'id': 12740, u'tenant': None}
>>>
```

**Comment by zachmoody** [comment]
I don't think bulk creation was added to NetBox until v2.3.
