### ISSUE TITLE
pynetbox 3.4.0 breaks on import (probably due to setuptools_scm usage)

### ISSUE THREAD

**Issue by mandarg** [digitalocean/pynetbox#67]
Repro inside virtualenv (sorry about the `pip` spam). I'm pretty sure this is due to 8f83639f143d0c863c654ebc658919cc17d50643, but don't know enough about `setuptools_scm` to quickly submit a patch.

```
$ pip install pynetbox==3.3.1
Collecting pynetbox==3.3.1
Collecting six==1.11.0 (from pynetbox==3.3.1)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting netaddr==0.7.18 (from pynetbox==3.3.1)
  Using cached https://files.pythonhosted.org/packages/04/9c/46c719f026dc87822ccce2530049f3c0865e85307b7ab50beb28008e10c0/netaddr-0.7.18-py2.py3-none-any.whl
Collecting requests==2.10.0 (from pynetbox==3.3.1)
  Using cached https://files.pythonhosted.org/packages/99/b4/63d99ba8e189c47d906b43bae18af4396e336f2b1bfec86af31efe2d2cb8/requests-2.10.0-py2.py3-none-any.whl
Installing collected packages: six, netaddr, requests, pynetbox
Successfully installed netaddr-0.7.18 pynetbox-3.3.1 requests-2.10.0 six-1.11.0
You are using pip version 7.1.2, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

$ python -c 'import pynetbox'

$ pip install pynetbox==3.4.0
Collecting pynetbox==3.4.0
Requirement already satisfied (use --upgrade to upgrade): six==1.* in ./lib/python2.7/site-packages (from pynetbox==3.4.0)
Requirement already satisfied (use --upgrade to upgrade): netaddr==0.* in ./lib/python2.7/site-packages (from pynetbox==3.4.0)
Collecting setuptools-scm==2.* (from pynetbox==3.4.0)
  Downloading https://files.pythonhosted.org/packages/4d/a0/371355cbd608ef1d865738b94f7681e2fe56ef951070a66a892f30042a86/setuptools_scm-2.1.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): requests==2.* in ./lib/python2.7/site-packages (from pynetbox==3.4.0)
Installing collected packages: setuptools-scm, pynetbox
  Found existing installation: pynetbox 3.3.1
    Uninstalling pynetbox-3.3.1:
      Successfully uninstalled pynetbox-3.3.1
Successfully installed pynetbox-0.0.0 setuptools-scm-2.1.0
You are using pip version 7.1.2, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

$ python -c 'import pynetbox'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mgokhale/sandbox/pynetbox-bug/lib/python2.7/site-packages/pynetbox/__init__.py", line 6, in <module>
    __version__ = get_version(root='..', relative_to=__file__)
  File "/Users/mgokhale/sandbox/pynetbox-bug/lib/python2.7/site-packages/setuptools_scm/__init__.py", line 119, in get_version
    parsed_version = _do_parse(root, parse)
  File "/Users/mgokhale/sandbox/pynetbox-bug/lib/python2.7/site-packages/setuptools_scm/__init__.py", line 97, in _do_parse
    "use git+https://github.com/user/proj.git#egg=proj" % root)
LookupError: setuptools-scm was unable to detect version for '/Users/mgokhale/sandbox/pynetbox-bug/lib/python2.7/site-packages'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```

**Comment by zachmoody** [comment]
:disappointed: I'll have a look at it as soon as possible.
