### ISSUE TITLE
pynetbox failed to post if custom field is selection type

### ISSUE THREAD

**Issue by a31amit** [digitalocean/pynetbox#70]
I am getting weird behavior for pynetbox, not sure if this some limitation of pynetbox or something I am doing wrong. 

I have a custom field for devices which is selection type. 
 - If I remove this custom field, it works
 - If i change custom field value to None, it also works [ using pynetbox or from netbox gui] 
 - but when in general, even I am not trying to update it. It fails. 

not sure if this netbox problem or pynetbox issue. 

To Reproduce 
- add a custom field with selection type having 3-4 selection value. 
- Query device and verify with serialize to see if that custom field is not showing as None
- if showing None, than make sure to choose some value from netbox GUI. 
- verify that its showing with label and value. something like this 'dev_discover_status': {'label': 'Completed', 'value': 9}
- update another value d.serial and d.save() 

```
In [1]: import pynetbox
In [2]: netbox = pynetbox.api('https://netbox.local', token=MYTOKEN, ssl_verify=False)
In [3]: d = netbox.dcim.devices.get(name=TEST_DEVICE_NAME)
In [4]: d.serialize()
Out[4]:
{'asset_tag': '0202',
 'cluster': None,
 'comments': '',
 'created': '2018-06-28',
 'custom_fields': {'dev_chassis_type': 'other',
  'dev_depreciation_percent': 25,
  'dev_discover_status': {'label': 'Completed', 'value': 9},
<<Truncate>>
}
In [5] d.serial = '01234'
In [6]: d.save()
---------------------------------------------------------------------------
RequestError                              Traceback (most recent call last)
<ipython-input-6-ad0d43fe2a3d> in <module>()
----> 1 d.save()

~/virtualenv/nv-snmp-env/lib/python3.4/site-packages/pynetbox/lib/response.py in save(self)
    235                     ssl_verify=self.api_kwargs.get('ssl_verify')
    236                 )
--> 237                 if req.put(self.serialize()):
    238                     return True
    239             else:

~/virtualenv/nv-snmp-env/lib/python3.4/site-packages/pynetbox/lib/query.py in put(self, data)
    268             return json.loads(req.text)
    269         else:
--> 270             raise RequestError(req)
    271
    272     def post(self, data):

RequestError: The request failed with code 500 Internal Server Error
```

**Comment by zachmoody** [comment]
I'll try and mock this up when I get a chance. Haven't done a lot of things with custom fields, but it is strange it's coming back with a 500. What do the NetBox logs say? What's a working curl look like?

**Comment by a31amit** [comment]
I haven't tried anything with curl because ```d.custom_fields['dev_discover_status'] = 10``` something like would let me update the value and it works. The problem is when I am don't want to update this value or pynetbox fetches existing values and serialize with key: value ( as a record, i believe) . 
and seems like trying to send similar key: value back to netbox 

it seems that netbox is expecting a value/number/byte object where as pynetbox is sending a key:value pair?

In [8]: http_client.HTTPConnection.debuglevel = 1
```
send: b'PUT /api/dcim/devices/40/ HTTP/1.1\r\nHost: netbox.local\r\nConnection: keep-alive\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nUser-Agent: python-requests/2.19.1\r\nContent-Type: application/json; version=2.3;\r\nauthorization: Token bogustokenvalue0000000000000000\r\nContent-Length: 865\r\n\r\n{"position": null, "name": " test-device.domain.tld", "site": 3, "cluster": null, "asset_tag": null, "tenant": 9, "serial": "avz", "status": 1, "primary_ip6": null, "vc_priority": null, "rack": 72, "parent_device": null, "custom_fields": {" "dev_depreciation_percent": null, "dev_discovery_status": {"value": 15, "label": "Failed"}, "dev_po_number": null}, "primary_ip4": 403, "id": 40, "virtual_chassis": null, "face": 0, "device_role": 9, "vc_position": null, "created": "2018-06-28", "device_type": 6, "primary_ip": 403, "comments": "", "display_name": "test-device.domain.tld", "last_updated": "2018-07-06T17:22:09.466562-07:00", "platform": 16}'
reply: 'HTTP/1.1 500 Internal Server Error\r\n'

```


Below is Netbox Logs - 
```
Internal Server Error: /api/dcim/devices/40/
Traceback (most recent call last):
  File "/opt/netbox/netbox_env/lib/python3.4/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/netbox/netbox_env/lib/python3.4/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/netbox/netbox_env/lib/python3.4/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/netbox/netbox_env/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/netbox/netbox_env/lib/python3.4/site-packages/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/netbox/netbox_env/lib/python3.4/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/opt/netbox/netbox_env/lib/python3.4/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/netbox/netbox_env/lib/python3.4/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/netbox/netbox_env/lib/python3.4/site-packages/rest_framework/mixins.py", line 69, in update
    serializer.is_valid(raise_exception=True)
  File "/opt/netbox/netbox_env/lib/python3.4/site-packages/rest_framework/serializers.py", line 236, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/opt/netbox/netbox_env/lib/python3.4/site-packages/rest_framework/serializers.py", line 434, in run_validation
    value = self.to_internal_value(data)
  File "/opt/netbox/netbox_env/lib/python3.4/site-packages/rest_framework/serializers.py", line 488, in to_internal_value
    validated_value = field.run_validation(primitive_value)
  File "/opt/netbox/netbox_env/lib/python3.4/site-packages/rest_framework/fields.py", line 523, in run_validation
    value = self.to_internal_value(data)
  File "/opt/netbox/netbox/extras/api/customfields.py", line 68, in to_internal_value
    value = int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'
```

**Comment by zachmoody** [comment]
Oh, I see what you mean. That _should_ be a somewhat straight-forward fix.
