### ISSUE TITLE
Uncaught exception when parsing address attributes with certain formats

### ISSUE THREAD

**Issue by explody** [digitalocean/pynetbox#83]
Right up front, this is really arguably netaddr problem, but their core issue may be harder to fix, and it's fixable here.

It appears that if an IP's fields contain a string that matches a certain pattern, netaddr.IPNetwork mistakes it for CIDR and attempts to parse it, but fails as it's not really valid CIDR, which produces an unexpected exception.

You should be able to replicate this by, for example, adding a description to an IP that triggers this problem (which is how we found it, with a circuit ID containing slashes in the description field).  Presumably, this would work on any field that takes text strings.  

We set an IP's decription to `22/XXXX/111111//XY`

Here's the actual exception:

```
Traceback (most recent call last):
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netaddr/ip/__init__.py", line 799, in parse_ip_network
    prefixlen = int(val2)
ValueError: invalid literal for int() with base 10: 'XXXX/111111//XY''
```

And here is replicating it with plain python3:

```
>>> import netaddr
>>> netaddr.IPNetwork('22/XXXX/111111//XY')
Traceback (most recent call last):
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netaddr/ip/__init__.py", line 799, in parse_ip_network
    prefixlen = int(val2)
ValueError: invalid literal for int() with base 10: 'XXXX/111111//XY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netaddr/ip/__init__.py", line 924, in __init__
    implicit_prefix, flags)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netaddr/ip/__init__.py", line 806, in parse_ip_network
    mask = IPAddress(val2, module.version, flags=INET_PTON)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netaddr/ip/__init__.py", line 280, in __init__
    % self.__class__.__name__)
ValueError: IPAddress() does not support netmasks or subnet prefixes! See documentation for details.
```

After digging around, I narrowed it down to the `_parse_values` method in `IPRecord`, wherein, the IP record's fields are parsed to create object attributes, which includes this, where strings from IP fields are passed to netaddr

```
                if isinstance(v, six.string_types):
                    try:
                        v = netaddr.IPNetwork(v)
                    except netaddr.AddrFormatError:
                        pass
```

Perhaps just catch ValueErrors as well?

**Comment by zachmoody** [comment]
Yeah, I think that's a fair solution. I was worried we might not be catching all the possible exceptions there.
